[package]
name = "rich-thumbnail-uploader"
description = "Thumbnail uploader for foo_discord_rich"
version = "0.3.2"
edition = "2024"
license = "AGPL-3.0-or-later"
repository = "https://github.com/cod3ddot/rich-thumbnail-uploader"
authors = ["cod3ddot <cod3ddot@proton.me>"]
readme = "README.md"
categories = ["command-line-utilities"]
publish = false

[badges]
maintenance = { status = "passively-maintained" }

[package.metadata.winresource]
OriginalFilename = "rich-thumbnail-uploader.exe"
LegalCopyright = "Copyright © 2025 cod3ddot@proton.me"
FileDescription = "Thumbnail uploader for foo_discord_rich"

[dependencies]
attohttpc = { version = "0.30", default-features = false, features = [
    "tls-native",
    "multipart-form",
] }
miniserde = { version = "0.1" }
image = { version = "0.25", default-features = false, features = [
    "jpeg",
    "png",
    "webp",
] }
thiserror = { version = "2" }
pico-args = { version = "0.5" }

[dev-dependencies]
tempfile = "3.10.1"

[build-dependencies]
winresource = "0.1.23"
embed-manifest = "1.3.1"

[profile.release]
opt-level = 'z'   # Optimize for size
lto = true        # Enable Link Time Optimization
codegen-units = 1 # Reduce number of codegen units to increase optimizations
panic = 'abort'   # Remove panic unwinding code
strip = true      # Strip symbols from binary

[lints.rust]
unsafe_code = "deny"
unused = "deny"
missing_debug_implementations = "deny"
trivial_casts = "deny"
trivial_numeric_casts = "deny"
single_use_lifetimes = "deny"
unreachable_pub = "warn"
elided_lifetimes_in_paths = "deny"
explicit_outlives_requirements = "deny"
