version = 1
SPDX-PackageName = "rich-thumbnail-uploader"
SPDX-PackageSupplier = "https://github.com/cod3ddot/rich-thumbnail-uploader"

[[annotations]]
path = [".github/workflows/build.yml"]
precedence = "override"
SPDX-FileCopyrightText = "2025 cod3ddot@proton.me"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = [
    ".gitignore",
    ".gitattributes",
    "Cargo.lock",
    "Cargo.toml",
    ".cargo/config.toml",
    "rustfmt.toml",
    "rust-toolchain.toml",
    "resources/app.ico",
    "resources/app.rc",
    "resources/app.manifest",
    "lefthook.yml",
]
precedence = "override"
SPDX-FileCopyrightText = "2025 cod3ddot@proton.me"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["README.md", "CHANGES.md", "docs/**/*"]
SPDX-FileCopyrightText = "2025 cod3ddot@proton.me"
SPDX-License-Identifier = "CC-BY-NC-SA-4.0"
