# Based on the template in https://github.com/FedericoPonzi/rust-ci
name: Build binaries

on:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:

jobs:
  check-client-id:
    name: Check if imgur client id secret exists
    runs-on: ubuntu-latest
    env:
      IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
    steps:
      - name: A/B Check
        if: ${{ env.IMGUR_CLIENT_ID == '' }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('IMGUR_CLIENT_ID secret not set!')

  check-style:
    name: Check Style
    needs: [check-client-id]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Run format check
        run: cargo fmt --all -- --check

      - name: Run unit + integration tests
        run: cargo test --locked --all-targets --all-features

      - name: Check REUSE compliance
        uses: fsfe/reuse-action@v5

  build:
    name: Build binary
    needs: [check-style]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-pc-windows-gnu]
    outputs:
      target: ${{ steps.set-output.outputs.target }}
    steps:
      - uses: actions/checkout@v4

      - name: Build target (release)
        id: build
        uses: houseabsolute/actions-rust-cross@v1
        with:
          target: ${{ matrix.target }}
          args: "--release --locked"
        env:
          IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}

      - name: Save target info
        id: set-output
        run: echo "target=${{ matrix.target }}" >> $GITHUB_OUTPUT

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: rich-thumbnail-uploader.exe
          path: target/${{ matrix.target }}/release/rich-thumbnail-uploader.exe

  create-release:
    name: Publish Release
    needs: [build]
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-pc-windows-gnu]
    steps:
      - uses: actions/checkout@v4

      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: rich-thumbnail-uploader.exe
          path: ./bin

      - name: Run UPX to reduce binary size
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          files: "./bin/rich-thumbnail-uploader.exe"
          args: -q --best --lzma

      - name: Generate SHA256 checksum
        id: checksum
        run: |
          sha256sum ./bin/rich-thumbnail-uploader.exe > ./bin/rich-thumbnail-uploader.exe.sha256

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_SIGNING_KEY }}" \
            | gpg --batch --allow-secret-key-import --import

      - name: Sign the checksum file
        run: |
          gpg --batch --yes \
            --armor --detach-sign ./bin/rich-thumbnail-uploader.exe.sha256

      - name: Extract latest changelog entry
        id: changelog
        run: |
            awk '/^## \[/ { if (found) exit; found=1 } found' CHANGES.md > latest_changes.md

      - name: Create GitHub Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/rich-thumbnail-uploader.exe
            bin/rich-thumbnail-uploader.exe.sha256
            bin/rich-thumbnail-uploader.exe.sha256.asc
          body_path: latest_changes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
